### ISSUE TITLE
Application will fail to open at times

### ISSUE THREAD

**Issue by lozanotux** [libredeb/lightpad#1]
When you use it will open right away but if you close it a try to open it again you have to try 3 to 6 times it varies before it will open again.

**Logs from terminal:**

> Gtk-Message: 12:50:43.204: Failed to load module "appmenu-gtk-module"
Gtk-Message: 12:50:45.419: Failed to load module "appmenu-gtk-module"
**
ERROR:arraylist.c:1181:gee_array_list_real_get: assertion failed: (index >= 0)
Bail out! ERROR:arraylist.c:1181:gee_array_list_real_get: assertion failed: (index >= 0)
Gtk-Message: 12:50:55.430: Failed to load module "appmenu-gtk-module"
**
ERROR:arraylist.c:1181:gee_array_list_real_get: assertion failed: (index >= 0)
Bail out! ERROR:arraylist.c:1181:gee_array_list_real_get: assertion failed: (index >= 0)
Gtk-Message: 12:50:56.651: Failed to load module "appmenu-gtk-module"
**
ERROR:arraylist.c:1181:gee_array_list_real_get: assertion failed: (index >= 0)
Bail out! ERROR:arraylist.c:1181:gee_array_list_real_get: assertion failed: (index >= 0)
Gtk-Message: 12:50:57.484: Failed to load module "appmenu-gtk-module"
**
ERROR:arraylist.c:1181:gee_array_list_real_get: assertion failed: (index >= 0)
Bail out! ERROR:arraylist.c:1181:gee_array_list_real_get: assertion failed: (index >= 0)
Gtk-Message: 12:50:58.312: Failed to load module "appmenu-gtk-module"**

**Comment by libredeb** [comment]
The issue was due to the fact that occasionally the Gee package throws a negative one (-1)... causing that the correct array element could not be obtained to graph the grid assigned to the page
