### ISSUE TITLE
Categorizing the apps

### ISSUE THREAD

**Issue by SethStormR** [libredeb/lightpad#12]
Hi,

It would be nice if lightpad have the option to show the apps in categories. When you have a lot of apps and games installed it can be tedious to navigate through without having them categorized.

regards

**Comment by libredeb** [comment]
Hi @SethStormR,

I understand the point, but it is not the focus that I want to give to lightpad. The original idea is to have something similar to what exists in the macOS world with launchpad. If we added features from other launchers, lightpad would become those launchers and lose its essence. If you want categories you can see other projects like slingswarm or slingscold-launcher.

Regards!
