### ISSUE TITLE
ARM64 build deb file please?

### ISSUE THREAD

**Issue by Botspot** [libredeb/lightpad#15]
I am the CEO of [Pi-Apps](https://github.com/Botspot/pi-apps) and [am interested](https://github.com/Botspot/pi-apps/issues/191) in adding Lightpad to the app store.  
As Pi-Apps is 32-bit RPiOS and 64-bit RPiOS compatible, it needs some way to install Lightpad on 64-bit installs.

TL;DR would you guys consider adding an arm64.deb release to the [Releases page](https://github.com/libredeb/lightpad/releases/tag/v0.0.8)?

**Comment by libredeb** [comment]
@Botspot yes, so far we have not had the need to create a deb for arm64 arch. We can compile one of course, but I honestly don't have the hardware to do it. If you can, try to read the next information: [Build a DEB Package](https://ostechnix.com/how-to-build-debian-packages-from-source/)

Only that you need is to set in the file `debian/control` the property `Architecture` with the correct value (arm64 in this case). Now has the value `any` that take the arch from your hardware in compilation time.

You can help us with this? If you can share me a deb file, I can update the release page to add the deb package to it. Regards!

**Comment by Botspot** [comment]
@libredeb Of course I could compile an arm64 deb.  
But that solution would not work well long-term. (I don't want to periodically compile a deb each time Lightpad is updated)

@libredeb, do you have a Raspberry Pi? If so, you can compile

> We can compile one of course, but I honestly don't have the hardware to do it.

Do you have a Raspberry Pi? If not, then who compiled the armhf deb? On a Raspberry Pi, you can easily compile it for arm64 or armhf. (perhaps with the help of [vdesktop](https://github.com/Botspot/vdesktop) if you only have one SD card to work with)

**Comment by fossfreedom** [comment]
@libredeb just a bit of a FYI ... whilst I cant help to produce an automatic build of arm64 deb built on Raspian, just to say for Ubuntu Budgie we do have an arm64 deb built for our raspi image. https://launchpad.net/~ubuntubudgie/+archive/ubuntu/backports/+packages?field.name_filter=lightpad&field.status_filter=published&field.series_filter=

**Comment by libredeb** [comment]
@fossfreedom ooh great! I did not know of the existence of it... I will include that package in the releases page. Thank you very much. Regards!
