### ISSUE TITLE
weird issue on budgie

### ISSUE THREAD

**Issue by amirzolal** [libredeb/lightpad#19]
Hi,

I have a weird issue on budgie, using the applet. So when I try to run tilix, the lightpad finds the app, when I press enter, nothing happens.

But, when I launch Tilix from Plank and have one (or more) Tilix windows open, launchpad runs another window of Tilix.
The same applies to gedit. 

Any ideas what the cause might be? 
BTW installation over Budgie welcome failed, so i installed with apt. I am on 20.04. 

Thanks,

Amir

**Comment by amirzolal** [comment]
Now - creating new launchers and not using the default ones (/usr/share/applications/com.gexperts.Tilix.desktop) with all the actions and stuff helps.

Also, it would help if I edited the launchers and removed the actions. But this is fully sufficient, I never launched the actions from plank.

**Comment by libredeb** [comment]
Mmmm i don't know why Lightpad is having that behavior. Several things come to my mind in this moment... for example, I remember that in Cinnamon desktop, in some cases, launchers (.desktop files) needs to have certain properties.

Let me try to reproduce the issue/bug... i will install budgie 20.04 in a VM and verify this behavior to debug the code and find a solution to this. Thanks for your comments!

**Comment by fossfreedom** [comment]
I strongly suspect this issue is due to the dbus-activatable problems - so solved now in UB - and will be available as "fixed/workaround" in v0.0.9

**Comment by libredeb** [comment]
Its solved with related [issue #28](https://github.com/libredeb/lightpad/issues/28). Try to compile Lightpad from last commit and test it!
