### ISSUE TITLE
It doesn't open apps than runs on terminal

### ISSUE THREAD

**Issue by lozanotux** [libredeb/lightpad#2]
This launcher can't launch my terminal based Apps, Htop for example. I am on XFCE.

Amazing work.

**Comment by libredeb** [comment]
It was not taken into account that the GIO package in old versions did not have a VFS implementation. Therefore, a strategy was implemented to execute terminal applications according to the desktop environment:

- **Debian based** `-->` x-terminal-emulator
- **GNOME** `-->` gnome-terminal
- **Pantheon** `-->` io.elementary.terminal
- **XFCE** `-->` xfce4-terminal
- **LXDE** `-->` lxterminal
- **LXqt** `-->` qterminal
