### ISSUE TITLE
sort order

### ISSUE THREAD

**Issue by fossfreedom** [libredeb/lightpad#3]
Hi,

  any chance that the sort order of the apps be in vala collate order (takes into account locale sorting for alphabetical) rather than the rather random order it is displayed at the moment?

**Comment by gonzalezb** [comment]
I second this would be nice to sort by alphabetical order not necessary but would be nice.

**Comment by libredeb** [comment]
@fossfreedom @gonzalezb do you say alphabetically by categories or by the applications? In itself it is not a bug but rather a feature request. I'm going to see organize these things. Thank for your support!

**Comment by fossfreedom** [comment]
Sort by applications.  I didnt see a filter by category option - but if there was one - then the feature request would be similar - sort what you see on the screen.

Thx!

**Comment by libredeb** [comment]
@fossfreedom ready! implemented in the last commit [#701f326](https://github.com/libredeb/lightpad/commit/701f32617a4c47b8e4484c33069a5c2dc21f7d03).

Big hug!
![order-az](https://user-images.githubusercontent.com/5141008/84938295-68140b00-b0b3-11ea-9355-599274285f33.png)
