### ISSUE TITLE
search-bar affected by GTK Theme

### ISSUE THREAD

**Issue by fossfreedom** [libredeb/lightpad#4]
![Screenshot from 2020-06-17 15-24-44](https://user-images.githubusercontent.com/996240/84910444-cbe80500-b0ae-11ea-97d0-abebf5264707.png)

The searchbar seems to be affected by the GTK Theme in use - some make the bar more visible than others.

note - the above is a snap package I am looking at for lightpad - I'll do a PR at some point!

Given that the background is dark - maybe the searchbar should have its CSS defined by the app?

Here is another example - this time the searchbar is truncated (default theme in Ubuntu Budgie 18.04 called Pocillo)

![Screenshot from 2020-06-17 15-19-26](https://user-images.githubusercontent.com/996240/84910811-4153d580-b0af-11ea-9523-d5481f48d3af.png)

**Comment by libredeb** [comment]
@fossfreedom thank you for your help testing LightPad, i have commited new code... you can do a **git pull** and compile again?

Yes, the searchbar has a CSS style defined in the file `/usr/share/lightpad/application.css` and shouldn't interfere with GTK themes. The searchbar truncated was a problem that we have already solved in the latest commits.

Please, follow the indications to compile and confirm that you are no longer experiencing these issues. By the way, what theme do you use when the search bar looks totally dark?

Regards!

**Comment by libredeb** [comment]
@fossfreedom if you can and wish... let me know your name and email to add you as contributor of project. Thank you!

**Comment by fossfreedom** [comment]
Thanks - the truncated theme and the search bar dark issues are resolved with the latest commits.

The snap of lightpad has a major issue at the moment - lightpad running as a snap only displays snap installs - not all installs.  I'll continue to look at this to see if its resolvable.

**Comment by libredeb** [comment]
@fossfreedom ok, thank you for your feedback... ok, snap install is another topic. I will have to test this issue (reproduce it) and fix it. I'll be focusing on this since it probably affects many users. Regards!

**Comment by libredeb** [comment]
@fossfreedom I tried to reproduce the error of the snaps but without success. Attached evidence. Regards!
![details](https://user-images.githubusercontent.com/5141008/85360009-77f27b80-b507-11ea-98dc-61622aba1ebc.png)
![spotify](https://user-images.githubusercontent.com/5141008/85360010-7923a880-b507-11ea-86e4-b0011eb52e76.png)

**Comment by fossfreedom** [comment]
Think there is a bit of confusion.... it's not an issue of showing snaps.
That works just fine!

I was raising an issue when lightpad was running as a snap itself.

This I have fixed and I will do a PR once the outstanding PR is dealt with.
Thx.
