### ISSUE TITLE
system locations are hardcoded

### ISSUE THREAD

**Issue by fossfreedom** [libredeb/lightpad#6]
raising low priority issue:

Whilst I was looking at creating a snap I noticed looking through the code that various system locations are hard-coded e.g. /usr/share/applications.

To be portable between distro's - this should be calculated at compile time - meson has various parameters such as --datadir that define where the file system data location is.

e.g. https://github.com/UbuntuBudgie/budgie-extras/blob/master/meson.build#L46

To pass compile time variable to vala you can use a config file

e.g. https://github.com/UbuntuBudgie/budgie-extras/blob/master/meson.build#L49

and

https://github.com/UbuntuBudgie/budgie-extras/blob/master/vapi/config.vapi

**Comment by libredeb** [comment]
Yes, there are things that as a developer I have not finished learning from this world of Vala and Meson... I have no intention of offering support for snap or flatpak, instead I have offered templates for DEB, RPM and Arch PKG. I will try to learn this from how to pass dynamic variables to Vala with meson to improve this that you are commenting on. Regards!
